apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  namespace: default
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "secure_production_db_password"
  JWT_SECRET: "nexus_arena_production_jwt_secret_key_998877"
